#!/usr/bin/env bash
# configure redirection route
sudo apt -y upgrade
sudo apt -y update
sudo apt -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i "54i\n\t}\n\n\tlocation /redirect_me/ {\n\t\treturn 301 https://github.com/rabiebn/;\n\t}" /etc/nginx/sites-available/default
sudo service nginx restart
