#!/usr/bin/env bash
# configure redirection route
sudo sed -i -e "s/=404;\n\t}\n/=404;\n\t}\n\n\tlocation /redirect_me/ {\n\t\treturn 301 https://github.com/rabiebn/;\n\t}/g" /etc/nginx/sites-enabled/afrolang.tech
