#!/usr/bin/env bash
# Configures Server so that localhost resolves to 127.0.0.2 and facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.new
sed -i -E 's/^(([0-9]{1,3}\.){3}[0-9]{1,3}\s*localhost)$/127.0.0.2       localhost/' ~/hosts.new
echo "8.8.8.8      facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
