#!/usr/bin/env bash
# Bash script to connect to a server without typing a password
Host 52.91.146.224
    HostName 52.91.146.224
    User ubuntu
    IdentityFile ~/.ssh/school
    PasswordAuthentication no
