#!/usr/bin/env bash
# Bash script to connect to a server without typing a password
Host 34.207.57.188
    HostName 34.207.57.188
    User ubuntu
    IdentityFile ~/.ssh/school
    PasswordAuthentication no
